services:
    table.factory:
        class: EMC\TableBundle\Table\TableFactory
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher, @table.session, @table.column.factory]
    
    table.session:
        class: EMC\TableBundle\Session\TableSession
        arguments: [@session]
    
    table.listener:
        class: EMC\TableBundle\Listener\TableListener
        arguments: [@table.session]
        tags:
            - { name: kernel.event_listener, event: table.pre_set_data, method: onPreSetData }
            - { name: kernel.event_listener, event: table.post_set_data, method: onPostSetData }
    
    table.extension:
        class: EMC\TableBundle\Twig\TableExtension
        arguments: [@twig, %emc_table.template%, %emc_table.extensions%]
        tags:
            -  { name: twig.extension }
            
    table.registry:
        class: EMC\TableBundle\Table\TableRegistry
        arguments: [@service_container, {}]

    table.column.factory:
        class: EMC\TableBundle\Column\ColumnFactory
        arguments: [@table.registry]

    table.column.text:
        class: EMC\TableBundle\Column\TextType
        tags:
            -  { name: table.type, alias: text }
            
    table.column.anchor:
        class: EMC\TableBundle\Column\AnchorType
        tags:
            -  { name: table.type, alias: anchor }
            
    table.column.datetime:
        class: EMC\TableBundle\Column\DatetimeType
        tags:
            -  { name: table.type, alias: datetime }
                            
    table.column.icon:
        class: EMC\TableBundle\Column\IconType
        tags:
            -  { name: table.type, alias: icon }
            
    table.column.button:
        class: EMC\TableBundle\Column\ButtonType
        tags:
            -  { name: table.type, alias: button }
            
    table.column.image:
        class: EMC\TableBundle\Column\ImageType
        tags:
            -  { name: table.type, alias: image }
            
    table.data_collector:
        class: EMC\TableBundle\Profiler\DataCollector\TableDataCollector
        tags:
            - { name: data_collector, template: "EMCTableBundle:Profiler:layout.html.twig", id: "table"  }
            
    table.data_collector.listener:
        class: EMC\TableBundle\Profiler\Listener\TableDataCollectorListener
        arguments: [@table.data_collector]
        tags:
            - { name: kernel.event_listener, event: table.pre_set_data, method: onPreSetData }
            - { name: kernel.event_listener, event: table.post_set_data, method: onPostSetData }

