language: php

sudo: false

php:
    - 5.5
    - 5.6

env:
  - SYMFONY_VERSION=2.6.*
  
before_script:
    - sudo apt-get -y -qq update
    - composer self-update
    - composer install --no-interaction
    - wget --quiet http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-precise-amd64.deb
    - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -qq install fontconfig libxrender1 xfonts-base xfonts-75dpi 
    - sudo dpkg -i wkhtmltox-0.12.2.1_linux-precise-amd64.deb
    - rm wkhtmltox-0.12.2.1_linux-precise-amd64.deb
    
script:
    - phpunit
    
cache:
    - bundler
    - apt

notifications:
    email:
        - chafiq.elmechrafi@table-bundle.com