language: php

sudo: required

services:
  - docker

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - docker pull chafiq/wkhtmltox
  - composer self-update
  - composer install --dev

script: phpunit --coverage-text

notifications:
  email:
    - chafiq.elmechrafi@table-bundle.com
