language: php

sudo: true

services:
  - docker

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer install --no-interaction
    - docker pull chafiq/wkhtmltox

script:
    - ./bin/phpunit

notifications:
  email:
    - chafiq.elmechrafi@table-bundle.com
